import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";
import { Tab } from "@headlessui/react";

const tabs = [
  {
    key: "all",
    display: "All"
  },
  {
    key: "landscape",
    display: "landscape"
  },
  {
    key: "oceans",
    display: "oceans"
  }
];

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="flex flex-col h-full bg-[url('/portfolio-bg.jpg')] bg-center  bg-cover">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-between items-center h-[90px] px-6 ">
        <div className="text-transparent">hm</div>
        <div>logo</div>
        <Link
          href="#"
          className="rounded-3xl bg-white px-3 py-1 text-stone-700 hover:bg-opacity-90"
        >
          Get in touch
        </Link>
      </header>
      <main className="grow h-full">
        <div className="flex items-center flex-col h-full">
          <Tab.Group>
            <Tab.List className="flex items-center gap-12">
              {tabs.map(tab => (
                <Tab className="p-1" key={tab.key}>
                  {({ selected }) => (
                    <span
                      className={selected ? "text-white" : "text-stone-600"}
                    >
                      {tab.display}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className="h-full bg-stone-900 bg-opacity-70 max-w-[900px] w-full p-2 sm:p-4 my-4">
              <Tab.Panel>All</Tab.Panel>
              <Tab.Panel>Landscape </Tab.Panel>
              <Tab.Panel>Oceans</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>
      <footer className="h-[60px] flex justify-center items-center">
        <h2>hello2</h2>
      </footer>
    </div>
  );
}
